# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectKisiKisiGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Import QtCore, QtGui, QtWidgets from PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets

# Class
class Ui_MainWindow(object):
    # Fungsi setupUI
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Label Data Mahasiswa
        self.dataMhsLb = QtWidgets.QLabel(self.centralwidget)
        self.dataMhsLb.setGeometry(QtCore.QRect(170, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dataMhsLb.setFont(font)
        self.dataMhsLb.setObjectName("dataMhsLb")

        # Label NIM
        self.nimLb = QtWidgets.QLabel(self.centralwidget)
        self.nimLb.setGeometry(QtCore.QRect(40, 330, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nimLb.setFont(font)
        self.nimLb.setObjectName("nimLb")

        # Label Nama
        self.namaLb = QtWidgets.QLabel(self.centralwidget)
        self.namaLb.setGeometry(QtCore.QRect(40, 350, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.namaLb.setFont(font)
        self.namaLb.setObjectName("namaLb")

        # Label Jurusan
        self.jurusanLb = QtWidgets.QLabel(self.centralwidget)
        self.jurusanLb.setGeometry(QtCore.QRect(40, 370, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.jurusanLb.setFont(font)
        self.jurusanLb.setObjectName("jurusanLb")

        # Label No. Telp
        self.telpLb = QtWidgets.QLabel(self.centralwidget)
        self.telpLb.setGeometry(QtCore.QRect(40, 390, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.telpLb.setFont(font)
        self.telpLb.setObjectName("telpLb")

        # LineEdit untuk NIM
        self.lineEditNim = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNim.setGeometry(QtCore.QRect(90, 330, 341, 16))
        self.lineEditNim.setObjectName("lineEditNim")

         # LineEdit untuk Nama
        self.lineEditNama = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNama.setGeometry(QtCore.QRect(90, 350, 341, 16))
        self.lineEditNama.setObjectName("lineEditNama")

         # LineEdit untuk Jurusan
        self.lineEditJrsn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditJrsn.setGeometry(QtCore.QRect(90, 370, 341, 16))
        self.lineEditJrsn.setObjectName("lineEditJrsn")

         # LineEdit untuk No.Telp
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 390, 341, 16))
        self.lineEdit_5.setObjectName("lineEdit_5")

        # Text Edit
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 70, 391, 241))
        self.textEdit.setObjectName("textEdit")

        # Widget
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(160, 410, 271, 21))
        self.widget.setObjectName("widget")

        # Horizontal Layout
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Push Button "Tambah"
        self.tambahBttn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tambahBttn.setFont(font)
        self.tambahBttn.setObjectName("tambahBttn")
        self.horizontalLayout.addWidget(self.tambahBttn)

          # Push Button "Edit"
        self.editBttn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.editBttn.setFont(font)
        self.editBttn.setObjectName("editBttn")
        self.horizontalLayout.addWidget(self.editBttn)

        # Push Button "Clear"
        self.clearBttn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clearBttn.setFont(font)
        self.clearBttn.setObjectName("clearBttn")
        self.horizontalLayout.addWidget(self.clearBttn)

        # Push Button "Hapus"
        self.hapusBttn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hapusBttn.setFont(font)
        self.hapusBttn.setObjectName("hapusBttn")
        self.horizontalLayout.addWidget(self.hapusBttn)

        # Menu Bar dan Status Bar
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Fungsi retranslateUi
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dataMhsLb.setText(_translate("MainWindow", "Data Mahasiswa"))
        self.nimLb.setText(_translate("MainWindow", "NIM"))
        self.namaLb.setText(_translate("MainWindow", "Nama"))
        self.jurusanLb.setText(_translate("MainWindow", "Jurusan"))
        self.telpLb.setText(_translate("MainWindow", "No. Telp"))
        self.tambahBttn.setText(_translate("MainWindow", "TAMBAH"))
        self.editBttn.setText(_translate("MainWindow", "EDIT"))
        self.clearBttn.setText(_translate("MainWindow", "CLEAR"))
        self.hapusBttn.setText(_translate("MainWindow", "HAPUS"))

    # Main
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
